import type { Bi } from '../../data/types'
import type { Card } from '../types'

const b = (zh: string, en: string): Bi => ({ zh, en })
const t = String.raw

/** Layer 4 — brain systems; each card is linked to the matching atlas tour. */
export const LAYER4: Card[] = [
  {
    id: 'sys-vision', layer: 4, tour: 'vision',
    title: b('视觉系统 ↔ 卷积网络 / ViT', 'Visual system ↔ CNNs / ViTs'),
    summary: b('脑-AI 对应最好的系统之一：任务训练的 CNN 能预测猴子颞下皮层的神经反应。', 'One of the best-matched systems: task-trained CNNs predict monkey inferior-temporal responses.'),
    brain: b('视网膜 → LGN → V1 → V2/V4 → IT 的腹侧通路逐级提取更复杂、更不变的特征；背侧通路处理位置与动作。眼睛每秒扫视约 3 次，主动选择看哪里；高层反馈调制低层。', 'Retina → LGN → V1 → V2/V4 → IT extracts increasingly complex, invariant features; the dorsal stream handles location and action. The eyes saccade ~3 times per second, actively choosing where to look; feedback from higher areas modulates lower ones.'),
    brainMath: [{ tex: t`r_{\text{IT}} \approx A\,h_{\text{CNN}}^{(L)}(x)`, caption: b('Yamins 等（2014）：IT 神经反应可由 CNN 高层特征的线性映射预测', 'Yamins et al. (2014): IT responses are linearly predictable from high CNN layers') }],
    ai: b('CNN 的卷积、池化、层级结构直接受视觉皮层启发；ViT 用注意力代替局部卷积。二者在物体识别上已超越人类基准，并能作为视觉皮层的定量模型。', 'CNN convolution, pooling and hierarchy were directly inspired by visual cortex; ViTs replace local convolution with attention. Both exceed human benchmarks in object recognition and serve as quantitative models of visual cortex.'),
    aiMath: [{ tex: t`h^{(l+1)} = \mathrm{pool}\big(\phi(W^{(l)} * h^{(l)})\big)`, caption: b('卷积层级', 'Convolutional hierarchy') }],
    corr: 'similar', evidence: 'established',
    diffs: [
      b('主动视觉：人通过眼动选择信息；主流模型被动处理整幅图像。', 'Active vision: humans select information by eye movements; models process whole images passively.'),
      b('稳健性：人对对抗扰动和分布变化稳健得多，识别新类别只需极少样本。', 'Robustness: humans are far more robust to adversarial perturbations and distribution shift, and learn new categories from few examples.'),
      b('循环与反馈：视觉皮层大量使用反馈，前馈 CNN 没有。', 'Recurrence: visual cortex relies on feedback; feedforward CNNs do not.'),
    ],
    principle: b('层级特征与不变性是原理，AI 已经学到。仍值得借鉴的是：主动采样、反馈推断，以及视觉与动作（背侧流）的紧密耦合。', 'Hierarchy and invariance are principles AI already has. Still worth borrowing: active sampling, feedback inference and tight vision–action coupling (dorsal stream).'),
    ideas: [b('机器人视觉采用“注视点 + 外周低分辨率”的主动感知，由不确定性驱动下一次注视。', 'Robot vision with a fovea + low-resolution periphery, choosing the next fixation by uncertainty.')],
    refs: ['yamins2014', 'rao1999'],
  },
  {
    id: 'sys-hearing', layer: 4, tour: 'hearing',
    title: b('听觉系统 ↔ 语音/音频网络', 'Auditory system ↔ speech/audio networks'),
    summary: b('任务训练的音频网络同样能复现人类听觉行为和皮层层级。', 'Task-trained audio networks likewise reproduce human hearing behaviour and cortical hierarchy.'),
    brain: b('耳蜗把声音分解成频率通道（类似滤波器组），脑干比较双耳时间与强度差来定位声源，听觉皮层逐级处理音高、音色和语音。注意可以在嘈杂环境中“挑出”一个说话人（鸡尾酒会效应）。', 'The cochlea splits sound into frequency channels (a filter bank); the brainstem compares interaural time and level to localise sources; auditory cortex processes pitch, timbre and speech hierarchically. Attention can pick one voice out of a crowd (the cocktail-party effect).'),
    brainMath: [{ tex: t`\Delta t_{\text{ITD}} \approx \frac{d}{c}\sin\theta`, caption: b('双耳时间差定位声源方向 θ（d 为双耳间距，c 为声速）', 'Interaural time difference locates direction θ (d = ear distance, c = speed of sound)') }],
    ai: b('音频模型通常从频谱图（短时傅里叶或梅尔滤波）出发；Kell 等（2018）训练的网络自然形成了与听觉皮层对应的处理层级。', 'Audio models usually start from spectrograms (STFT or mel filter banks); networks trained by Kell et al. (2018) spontaneously developed a hierarchy matching auditory cortex.'),
    aiMath: [{ tex: t`X(t,f) = \Big|\sum_n x[n]\,w[n - t]\,e^{-i2\pi f n}\Big|`, caption: b('短时傅里叶变换：工程版的“耳蜗”', 'Short-time Fourier transform: an engineering “cochlea”') }],
    corr: 'similar', evidence: 'established',
    diffs: [
      b('双耳空间听觉和主动听（转头、注意）在主流模型中很少体现。', 'Binaural spatial hearing and active listening (head turns, attention) are rare in mainstream models.'),
      b('人的听觉与发声形成闭环（听到自己说话）；多数模型只听不说，或只说不听。', 'Human hearing forms a loop with speaking (hearing yourself); most models only listen or only speak.'),
    ],
    principle: b('原理：频率分解 + 层级处理 + 注意选择性，以及感知与产出的闭环。', 'Principle: frequency decomposition + hierarchy + attentional selection, and a perception–production loop.'),
    ideas: [b('为语音智能体加入“自我监听”回路，用听到的自身输出实时纠错。', 'Give speech agents a self-monitoring loop that corrects output from what they hear themselves say.')],
    refs: ['kell2018', 'hickok2007'],
  },
  {
    id: 'sys-touch', layer: 4, tour: 'touch',
    title: b('躯体感觉与痛觉 ↔ 触觉传感（薄弱）', 'Somatosensation & pain ↔ tactile sensing (weak)'),
    summary: b('人的皮肤有精细的“身体地图”和痛觉情绪通路；AI 的触觉与身体感还很初级。', 'Humans have a fine-grained body map and an affective pain pathway; AI touch and body sense are rudimentary.'),
    brain: b('皮肤中的多种感受器（压力、振动、温度、痛）经脊髓到丘脑，再到中央后回，那里按“感觉小人”排列成拓扑地图，相邻身体部位对应相邻皮层。痛觉另有一条通往前扣带回和岛叶的情绪通路，产生“要避开”的动机。脊髓反射能在大脑参与之前完成保护动作。', 'Diverse skin receptors (pressure, vibration, temperature, pain) project via spinal cord and thalamus to the postcentral gyrus, laid out as a topographic homunculus. Pain also runs an affective route to anterior cingulate and insula, creating the motivation to avoid. Spinal reflexes protect before the brain is involved.'),
    brainMath: [{ tex: t`w_i \leftarrow w_i + \eta\,h_{c,i}\,(x - w_i),\quad c = \arg\min_k \|x - w_k\|`, caption: b('自组织映射（Kohonen 1982）：相邻单元学会相邻输入，形成类似“感觉小人”的拓扑地图', 'Self-organising map (Kohonen 1982): neighbouring units learn neighbouring inputs, forming a homunculus-like topographic map') }],
    ai: b('机器人触觉传感器（电子皮肤、GelSight 等）正在发展，但与视觉相比数据少、模型弱；“痛觉”通常被简化为硬编码的安全约束或负奖励。', 'Robot tactile sensors (e-skin, GelSight…) are advancing, but data and models lag far behind vision; “pain” is usually reduced to hard-coded safety limits or negative reward.'),
    corr: 'crude', evidence: 'established',
    diffs: [
      b('人的全身触觉密集、多模态；机器人通常只在指尖有少量传感器。', 'Human touch is dense and multimodal across the body; robots usually have a few fingertip sensors.'),
      b('痛不只是负奖励，还带来注意、学习和保护行为的全局改变。', 'Pain is not just negative reward — it globally reshapes attention, learning and protective behaviour.'),
      b('快速反射与慢速认知的分层控制在机器人中很少见。', 'Layered fast-reflex/slow-cognition control is rare in robots.'),
    ],
    principle: b('原理：拓扑化的身体地图、分层（反射 → 皮层）的保护控制，以及把“伤害”变成全局学习信号。', 'Principle: topographic body maps, layered protective control (reflex → cortex) and turning harm into a global learning signal.'),
    ideas: [
      b('机器人控制分层：底层局部反射（毫秒级、无需大模型），上层慢速规划。', 'Layer robot control: local millisecond reflexes below, slow planning above.'),
      b('把“疼痛信号”设计为同时调节注意、学习率与动作约束的多重信号。', 'Design a pain signal that simultaneously modulates attention, learning rate and action constraints.'),
    ],
    refs: ['kohonen1982', 'craig2002'],
  },
  {
    id: 'sys-motor', layer: 4, tour: 'motor',
    title: b('运动系统 ↔ 机器人控制 / 视觉-语言-动作模型', 'Motor system ↔ robot control / vision-language-action models'),
    summary: b('人能灵巧、柔顺、快速适应地运动；机器人在这方面仍远远落后。', 'Humans move dexterously, compliantly and adapt fast; robots still lag far behind.'),
    brain: b('运动由多个回路协作完成：前运动区和辅助运动区计划，基底节选择动作，初级运动皮层下达指令，小脑用前向模型预测动作结果并快速校正，脊髓执行和反射。大脑的运动控制可以用“最优反馈控制”来描述（Todorov & Jordan 2002）：只纠正与任务相关的偏差。', 'Movement is a collaboration: premotor/SMA plan, basal ganglia select, M1 commands, the cerebellum predicts outcomes with forward models and corrects quickly, and the spinal cord executes and reflexes. Motor control is well described by optimal feedback control (Todorov & Jordan 2002): correct only task-relevant deviations.'),
    brainMath: [
      { tex: t`\hat x_{t+1} = f(x_t, u_t)\quad(\text{forward model}),\qquad u_t = \pi(x_t, x^{*})\quad(\text{inverse model})`, caption: b('小脑内部模型（Wolpert, Miall & Kawato 1998）', 'Cerebellar internal models (Wolpert, Miall & Kawato 1998)') },
      { tex: t`\min_{\pi}\ \mathbb{E}\Big[\sum_t x_t^{\top}Qx_t + u_t^{\top}Ru_t\Big]`, caption: b('最优反馈控制的代价函数', 'Optimal-feedback-control cost') },
    ],
    ai: b('机器人学使用模型预测控制、强化学习和模仿学习；视觉-语言-动作模型（如 RT-2）把网络知识迁移到机器人动作。世界模型（Dreamer 等）提供了学习型的前向模型。', 'Robotics uses MPC, RL and imitation learning; vision-language-action models (e.g. RT-2) transfer web knowledge to robot actions; world models (Dreamer…) provide learned forward models.'),
    corr: 'crude', evidence: 'established',
    diffs: [
      b('适应速度：人几次尝试就能适应新工具或负重；机器人往往需要大量数据重新训练。', 'Adaptation: humans adapt to a new tool or load within a few tries; robots often need extensive retraining.'),
      b('分层与并行：大脑同时运行反射、小脑校正和皮层规划；多数机器人策略是单一网络。', 'Hierarchy and parallelism: the brain runs reflexes, cerebellar correction and cortical planning at once; most robot policies are one network.'),
      b('身体：柔顺的肌肉骨骼和密集的本体感觉是硬件层面的巨大差距。', 'Body: compliant musculoskeletal hardware and dense proprioception are a huge hardware gap.'),
    ],
    principle: b('原理：前向模型 + 传出副本（预测自己动作的后果），多时间尺度的分层控制，以及只纠正与任务相关的误差。', 'Principle: forward models + efference copies (predicting the consequences of one’s own actions), multi-timescale hierarchical control, and correcting only task-relevant errors.'),
    ideas: [b('在大策略模型下方加一个小型、在线学习的“小脑模块”：用前向模型预测误差快速修正动作。', 'Add a small online-learning “cerebellar module” under a large policy that quickly corrects actions from forward-model errors.')],
    refs: ['wolpert1998', 'todorov2002', 'brohan2023', 'hafner2023'],
  },
  {
    id: 'sys-language', layer: 4, tour: 'language',
    title: b('语言系统 ↔ 大语言模型', 'Language system ↔ large language models'),
    summary: b('大语言模型的内部表示能预测大脑语言区的反应，但它的学习方式与人截然不同。', 'LLM representations predict brain responses in language areas — but they learn in a very different way.'),
    brain: b('语言网络以左侧颞叶和额下回为核心：Wernicke 区理解语音，颞中回存储词义，弓状束连接到 Broca 区组织产出（Hickok & Poeppel 2007）。儿童在与人互动、指物、行动中学会语言，接触的语言量比大模型的训练语料少几个数量级。', 'The language network centres on left temporal cortex and inferior frontal gyrus: Wernicke’s area for speech, middle temporal gyrus for meaning, the arcuate fasciculus to Broca’s area for production (Hickok & Poeppel 2007). Children learn through interaction, pointing and action, from orders of magnitude less language than LLM training corpora.'),
    brainMath: [{ tex: t`r_{\text{brain}}(w_t) \approx A\,h_{\text{LLM}}(w_{\le t})`, caption: b('Schrimpf 等（2021）：下一个词预测越好的模型，越能预测大脑语言区的反应', 'Schrimpf et al. (2021): models better at next-word prediction better predict language-area responses') }],
    ai: b('大语言模型用 Transformer 做下一个词预测，在语言理解与生成上已接近或超过人类的许多基准。', 'LLMs do next-token prediction with Transformers and approach or exceed humans on many language benchmarks.'),
    aiMath: [{ tex: t`\mathcal{L} = -\sum_t \log p_\theta\big(w_t \mid w_{<t}\big)`, caption: b('自回归语言建模', 'Autoregressive language modelling') }],
    corr: 'similar', evidence: 'debated',
    diffs: [
      b('接地：人的词语与感知、行动、身体经验相连；LLM 的词语主要与其他词相连。', 'Grounding: human words connect to perception, action and bodily experience; LLM words connect mainly to other words.'),
      b('数据效率：人用少得多的语言输入学会语言。', 'Data efficiency: humans learn language from far less input.'),
      b('学习方式：人在对话与社会互动中持续学习；LLM 预训练后基本固定。', 'Learning: humans learn continually through dialogue and social interaction; LLMs are largely fixed after pretraining.'),
    ],
    principle: b('“预测下一个词”与大脑语言区的预测性处理一致，这是被证实的原理。需要补上的是接地、社会互动学习和持续学习。', 'Next-word prediction aligns with predictive processing in language areas — a validated principle. Missing: grounding, social-interactive learning and continual learning.'),
    ideas: [b('把语言模型接到具身智能体上，用行动的结果作为语言学习的监督信号。', 'Attach language models to embodied agents and use action outcomes as supervision for language learning.')],
    refs: ['hickok2007', 'schrimpf2021', 'vaswani2017', 'lake2017'],
  },
  {
    id: 'sys-memory', layer: 4, tour: 'memory',
    title: b('记忆系统 ↔ 上下文窗口 / 检索增强 / 经验回放', 'Memory systems ↔ context windows / RAG / experience replay'),
    summary: b('大脑用“快速的海马 + 慢速的新皮层”解决稳定性与可塑性的矛盾；AI 只有零散的替代。', 'The brain resolves stability vs plasticity with a fast hippocampus + slow neocortex; AI has only piecemeal substitutes.'),
    brain: b('互补学习系统理论（McClelland 1995; Kumaran 2016）：海马一次就能把一段经历绑定存储，新皮层慢慢地提取统计规律；睡眠中海马回放经历，逐渐教会新皮层。海马-内嗅系统还用位置细胞和网格细胞构建结构化的“认知地图”，Tolman–Eichenbaum 机器（TEM）把它形式化，并被证明与 Transformer 存在形式上的联系。', 'Complementary learning systems (McClelland 1995; Kumaran 2016): the hippocampus binds an episode in one shot, the neocortex slowly extracts statistics, and hippocampal replay during sleep gradually teaches the cortex. The hippocampal–entorhinal system also builds structured cognitive maps with place and grid cells; the Tolman–Eichenbaum Machine (TEM) formalises this and relates to Transformers.'),
    brainMath: [{ tex: t`M \leftarrow M + \eta\,v\,k^{\top},\qquad \hat v = M\,q`, caption: b('海马式快速联想存储（一次写入、按线索读取）', 'Hippocampus-like fast associative storage (one-shot write, cued read)') }],
    ai: b('上下文窗口相当于短期工作记忆；检索增强生成（RAG）从外部库检索文本；DQN 的经验回放借鉴了海马回放；TEM 与 Transformer 的联系（Whittington 2022）为结构化记忆提供了新方向。', 'Context windows act like working memory; retrieval-augmented generation (RAG) fetches external text; DQN’s experience replay borrowed from hippocampal replay; the TEM–Transformer link (Whittington 2022) points to structured memory.'),
    corr: 'crude', evidence: 'established',
    diffs: [
      b('情景性：人的记忆带有时间、地点、情绪上下文；RAG 检索的是无上下文的文本片段。', 'Episodic: human memories carry time, place and emotional context; RAG retrieves context-free text chunks.'),
      b('巩固：人会把经历逐渐转化为知识；AI 的检索库与模型权重之间没有自动的巩固过程。', 'Consolidation: humans gradually turn episodes into knowledge; AI has no automatic consolidation between the store and the weights.'),
      b('遗忘管理：大脑主动选择保留什么；AI 要么全留、要么被覆盖。', 'Forgetting: the brain chooses what to keep; AI keeps everything or overwrites.'),
    ],
    principle: b('原理：快、慢两套学习系统配合回放，并用结构化的关系表示（认知地图）支持泛化。', 'Principle: fast and slow learning systems coupled by replay, with structured relational representations (cognitive maps) supporting generalisation.'),
    ideas: [
      b('为智能体设计“情景记忆库 + 定期离线巩固进权重”的双系统。', 'Give agents an episodic store plus periodic offline consolidation into weights.'),
      b('按新奇度和情绪/奖赏强度决定写入与保留的优先级。', 'Prioritise writing and retention by novelty and emotional/reward salience.'),
    ],
    refs: ['mcclelland1995', 'kumaran2016', 'whittington2020', 'whittington2022', 'lewis2020', 'mnih2015'],
  },
  {
    id: 'sys-fear', layer: 4, tour: 'fear',
    title: b('情绪系统 ↔（基本缺失）', 'Emotion system ↔ (largely absent)'),
    summary: b('情绪是快速切换全身状态、调节学习和决策的机制；AI 基本没有对应物。', 'Emotion rapidly switches the whole-body state and tunes learning and decisions; AI has almost no counterpart.'),
    brain: b('杏仁核通过快速的“低通路”检测威胁，立即改变全脑与身体状态：注意收窄、心率上升、记忆增强、行为倾向改变（LeDoux 2000）。躯体标记假说（Damasio 1996）认为，情绪信号帮助前额叶在复杂选择中快速排除不利选项。恐惧学习本身也可以用预测误差描述。', 'The amygdala detects threat via a fast low road and instantly shifts brain and body state: narrowed attention, higher heart rate, stronger memory, changed action tendencies (LeDoux 2000). The somatic-marker hypothesis (Damasio 1996) proposes emotional signals help prefrontal cortex prune bad options quickly. Fear learning itself follows prediction-error rules.'),
    brainMath: [{ tex: t`\Delta V = \alpha\,(\lambda - V)`, caption: b('Rescorla–Wagner 规则描述的恐惧条件化：V 是对威胁的预期，λ 是实际结果', 'Fear conditioning under the Rescorla–Wagner rule: V is the expected threat, λ the actual outcome') }],
    ai: b('AI 中最接近的是负奖励和安全约束；少数工作研究“情绪”作为元控制信号。大语言模型能识别和表达情绪词汇，但没有功能性的情绪状态。', 'The closest AI analogues are negative rewards and safety constraints; a few works treat “emotion” as a meta-control signal. LLMs recognise and express emotion words but have no functional emotional state.'),
    corr: 'absent', evidence: 'debated',
    diffs: [
      b('情绪是全局状态切换，同时改变注意、学习率、风险偏好和身体；AI 只有标量奖励。', 'Emotion is a global state switch changing attention, learning rate, risk preference and body at once; AI has scalar reward.'),
      b('情绪反应比深思熟虑快得多，为紧急情况提供“捷径”。', 'Emotional responses are far faster than deliberation, giving emergency shortcuts.'),
    ],
    principle: b('原理：用少数快速、全局的状态变量（威胁、兴奋、满足）调制整个系统的计算模式。', 'Principle: a few fast global state variables (threat, arousal, satisfaction) that modulate the whole system’s computational mode.'),
    ideas: [b('为机器人设计“情绪状态向量”：由威胁/新奇/成功等信号驱动，同时调节探索温度、学习率、动作速度与记忆写入优先级。', 'Design an emotion-state vector for robots, driven by threat/novelty/success and jointly tuning exploration temperature, learning rate, action speed and memory-write priority.')],
    refs: ['ledoux2000', 'damasio1996', 'schultz1997'],
  },
  {
    id: 'sys-reward', layer: 4, tour: 'reward',
    title: b('奖赏系统 ↔ 时序差分强化学习', 'Reward system ↔ temporal-difference RL'),
    summary: b('神经科学与 AI 对应最好的例子：多巴胺神经元编码的正是 TD 误差。', 'The best neuroscience–AI match: dopamine neurons encode the TD error.'),
    brain: b('中脑多巴胺神经元在意外奖赏时爆发放电，在奖赏被完全预测时不再反应，在预期奖赏缺失时降低放电——与 TD 学习的误差信号完全一致（Schultz, Dayan & Montague 1997）。后来发现不同多巴胺神经元编码不同乐观程度的预测，构成奖赏的分布（Dabney 2020），与分布式强化学习对应。', 'Midbrain dopamine neurons burst for unexpected reward, stop responding once reward is predicted, and dip when an expected reward is missing — exactly the TD error (Schultz, Dayan & Montague 1997). Later work showed different dopamine neurons encode predictions of different optimism, forming a distribution over reward (Dabney 2020), matching distributional RL.'),
    brainMath: [{ tex: t`\delta_t = r_t + \gamma\,V(s_{t+1}) - V(s_t),\qquad V(s_t) \leftarrow V(s_t) + \alpha\,\delta_t`, caption: b('时序差分误差 ≈ 多巴胺信号', 'TD error ≈ dopamine signal') }],
    ai: b('TD 学习、actor-critic（基底节中纹状体 ≈ critic/actor）、DQN 等构成了现代强化学习的核心；分布式强化学习反过来启发了神经科学研究。', 'TD learning, actor-critic (striatum ≈ critic/actor) and DQN form the core of modern RL; distributional RL in turn inspired neuroscience.'),
    corr: 'iso', evidence: 'established',
    diffs: [
      b('奖赏来源：人的奖赏来自内在需求、社会认可、好奇心等多种来源；AI 通常只有外部给定的单一奖赏。', 'Reward sources: human reward comes from internal needs, social approval, curiosity…; AI usually has one externally specified reward.'),
      b('“想要”与“喜欢”在大脑中是分离的系统；AI 没有这种区分。', '“Wanting” and “liking” are separate brain systems; AI has no such split.'),
    ],
    principle: b('原理（已被 AI 采用）：用预测误差驱动价值学习。仍需借鉴的是多来源、随需求变化的奖赏。', 'Principle (already adopted): prediction-error-driven value learning. Still to borrow: multiple reward sources that change with needs.'),
    ideas: [b('把奖赏分解为多个内部驱力通道（能量、安全、新奇、社会），各自有 TD 误差，由稳态状态加权。', 'Decompose reward into internal drive channels (energy, safety, novelty, social), each with its own TD error, weighted by homeostatic state.')],
    refs: ['schultz1997', 'dabney2020', 'daw2005', 'mnih2015'],
  },
  {
    id: 'sys-homeostasis', layer: 4, tour: 'homeostasis',
    title: b('稳态与内感受 ↔（缺失）', 'Homeostasis & interoception ↔ (absent)'),
    summary: b('人的目标最终来自“维持身体活下去”；AI 没有身体，也就没有自发的目标来源。', 'Human goals ultimately come from keeping the body alive; AI has no body and so no intrinsic source of goals.'),
    brain: b('下丘脑、脑干和岛叶持续监测体温、能量、水分、心率等内部状态（内感受，Craig 2002），并通过神经（交感/副交感）和激素（HPA 轴）两条通路调节身体。饥饿、口渴、疲劳这些驱力决定了什么东西“有价值”。', 'Hypothalamus, brainstem and insula continuously monitor temperature, energy, water, heart rate (interoception, Craig 2002) and regulate the body via neural (sympathetic/parasympathetic) and hormonal (HPA) routes. Drives like hunger, thirst and fatigue determine what is valuable.'),
    brainMath: [{ tex: t`D(H_t) = \Big(\sum_i \big|h_i^{*} - h_{i,t}\big|^{n}\Big)^{1/m},\qquad r_t = D(H_t) - D(H_{t+1})`, caption: b('稳态强化学习（Keramati & Gutkin 2014）：奖赏 = 离理想内部状态的距离减少量', 'Homeostatic RL (Keramati & Gutkin 2014): reward = reduction in distance from the ideal internal state') }],
    ai: b('主流 AI 没有内部状态需要维持。稳态强化学习、基于好奇心的内在奖励（Pathak 2017）是少数尝试。', 'Mainstream AI has no internal state to maintain. Homeostatic RL and curiosity-based intrinsic reward (Pathak 2017) are rare attempts.'),
    corr: 'absent', evidence: 'established',
    diffs: [
      b('目标来源：人的目标由身体需求产生；AI 的目标由人给定。', 'Goal source: human goals arise from bodily needs; AI goals are given by people.'),
      b('自我模型：人对自己的身体有持续更新的内部模型；AI 没有。', 'Self-model: humans maintain a continuously updated model of their own body; AI does not.'),
    ],
    principle: b('原理：智能体要有需要维持的内部变量，价值来自这些变量的调节。这可能是产生自主目标、自主学习的关键。', 'Principle: an agent should have internal variables to keep in range, with value arising from regulating them — possibly key to autonomous goals and learning.'),
    ideas: [b('为机器人定义内部变量（电量、温度、磨损、不确定性），用稳态强化学习产生内在奖励，并与外部任务奖励组合。', 'Give robots internal variables (battery, temperature, wear, uncertainty), derive intrinsic reward with homeostatic RL, and combine it with task reward.')],
    refs: ['craig2002', 'keramati2014', 'pathak2017'],
  },
  {
    id: 'sys-sleep', layer: 4, tour: 'sleep',
    title: b('睡眠与离线学习 ↔ 回放 / 生成式回放 / wake-sleep', 'Sleep & offline learning ↔ replay / generative replay / wake-sleep'),
    summary: b('大脑每天花三分之一时间离线整理：回放、巩固、重新归一化突触。', 'The brain spends a third of each day offline: replaying, consolidating and renormalising synapses.'),
    brain: b('深睡时海马以压缩的时间尺度回放白天的活动序列（Wilson & McNaughton 1994），与新皮层的慢波和纺锤波协同，把记忆转存到皮层。突触稳态假说认为，睡眠会整体下调白天增强的突触，恢复信噪比和学习能力（Tononi & Cirelli 2014）。REM 睡眠中的“做梦”可能是生成模型的离线采样。', 'In deep sleep the hippocampus replays the day’s activity sequences in compressed time (Wilson & McNaughton 1994), coordinated with cortical slow waves and spindles to transfer memories. The synaptic homeostasis hypothesis holds that sleep globally downscales synapses strengthened during the day, restoring signal-to-noise and the capacity to learn (Tononi & Cirelli 2014). REM dreaming may be offline sampling from a generative model.'),
    brainMath: [{ tex: t`w_{ij} \leftarrow \kappa\,w_{ij},\ \ \kappa < 1\ \ (\text{sleep downscaling})`, caption: b('突触稳态：睡眠中按比例整体下调（示意）', 'Synaptic homeostasis: proportional downscaling during sleep (schematic)') }],
    ai: b('经验回放（DQN）、生成式回放（Shin 2017）用生成模型“做梦”来缓解遗忘；wake-sleep 算法（Hinton 1995）交替训练识别和生成网络；Dreamer 在世界模型的想象中训练策略。', 'Experience replay (DQN) and generative replay (Shin 2017) use a generative model to “dream” and reduce forgetting; the wake-sleep algorithm (Hinton 1995) alternates recognition and generative training; Dreamer trains policies in world-model imagination.'),
    aiMath: [{ tex: t`\mathcal{L} = \mathbb{E}_{x\sim D_{\text{new}}}\,\ell(x) + \lambda\,\mathbb{E}_{\tilde x\sim G_{\text{old}}}\,\ell(\tilde x)`, caption: b('生成式回放：新数据 + 旧生成器“梦到”的数据', 'Generative replay: new data + samples “dreamt” by the old generator') }],
    corr: 'crude', evidence: 'debated',
    diffs: [
      b('大脑有固定的离线周期并区分不同阶段（NREM 回放、REM 重组）；多数 AI 系统训练完就一直在线推理。', 'The brain has regular offline periods with distinct phases (NREM replay, REM recombination); most AI systems infer continuously after training.'),
      b('睡眠还负责突触的整体再归一化与“清理”；AI 很少有对应的维护过程。', 'Sleep also renormalises and “cleans up” synapses; AI rarely has an equivalent maintenance process.'),
    ],
    principle: b('原理：在线收集经验，离线整理知识；回放顺序和选择由重要性决定；周期性地重新归一化权重。', 'Principle: collect experience online, organise knowledge offline; prioritise replay by importance; periodically renormalise weights.'),
    ideas: [b('为长期运行的机器人设计“睡眠周期”：停止交互，回放当天情景、蒸馏进主模型、整体收缩权重并评估遗忘。', 'Give long-running robots a sleep cycle: stop interacting, replay the day’s episodes, distil into the main model, globally shrink weights and check forgetting.')],
    refs: ['wilson1994', 'tononi2014', 'hinton1995', 'shin2017', 'hafner2023', 'saper2005'],
  },
  {
    id: 'sys-attention', layer: 4, tour: 'attention',
    title: b('注意与执行控制 ↔ 注意力机制 / 门控', 'Attention & executive control ↔ attention mechanisms / gating'),
    summary: b('名字一样，机制不同：大脑的注意是容量有限、目标驱动的选择；Transformer 的注意力是对所有内容的加权路由。', 'Same name, different mechanism: brain attention is capacity-limited, goal-driven selection; Transformer attention is weighted routing over everything.'),
    brain: b('前额叶在工作记忆中保持目标，并自上而下偏置感觉处理（Miller & Cohen 2001）；基底节像门控一样决定什么信息被写入或更新工作记忆（Frank 2001）。全局工作空间理论认为，只有少数信息能进入一个容量有限、全脑广播的“工作空间”（Dehaene & Changeux 2011）。大脑还会根据不确定性在“习惯”和“深思熟虑”两套控制系统之间切换（Daw 2005）。', 'Prefrontal cortex holds goals in working memory and biases sensory processing top-down (Miller & Cohen 2001); the basal ganglia gate what enters or updates working memory (Frank 2001). Global workspace theory says only a little information reaches a capacity-limited, brain-wide broadcast workspace (Dehaene & Changeux 2011). The brain also arbitrates between habitual and deliberative control by uncertainty (Daw 2005).'),
    brainMath: [{ tex: t`w_{\text{MB}} = \frac{\sigma^{-2}_{\text{MB}}}{\sigma^{-2}_{\text{MB}} + \sigma^{-2}_{\text{MF}}}`, caption: b('按不确定性仲裁：更可靠的系统获得更大的控制权（Daw 2005 的思想）', 'Uncertainty-based arbitration: the more reliable controller gets more weight (after Daw 2005)') }],
    ai: b('Transformer 注意力对所有 token 做基于内容的加权；MoE 路由实现条件计算；“慢思考”推理模型在推理时花更多计算，但切换机制多是人为设定。', 'Transformer attention weights all tokens by content; MoE routing gives conditional compute; “slow-thinking” reasoning models spend more compute at inference, but switching is mostly hand-set.'),
    aiMath: [{ tex: t`\mathrm{Attention}(Q,K,V) = \mathrm{softmax}\Big(\frac{QK^{\top}}{\sqrt{d}}\Big)V`, caption: b('缩放点积注意力', 'Scaled dot-product attention') }],
    corr: 'similar', evidence: 'debated',
    diffs: [
      b('容量：大脑的注意有严格的瓶颈（工作记忆约 4 项）；Transformer 可以同时关注上万个 token。', 'Capacity: brain attention has a hard bottleneck (~4 working-memory items); Transformers attend to tens of thousands of tokens.'),
      b('驱动：大脑的注意由目标和显著性共同驱动；Transformer 由内容相似度驱动。', 'Drive: brain attention is driven by goals and salience; Transformer attention by content similarity.'),
      b('元控制：大脑会自动在快、慢系统间切换；AI 很少能自己判断何时该深思。', 'Meta-control: the brain switches between fast and slow systems automatically; AI rarely decides for itself when to deliberate.'),
    ],
    principle: b('原理：容量有限的工作空间迫使系统做选择与抽象；门控决定什么进入工作记忆；按不确定性分配“思考”的计算量。', 'Principle: a capacity-limited workspace forces selection and abstraction; gating controls what enters working memory; allocate deliberation compute by uncertainty.'),
    ideas: [
      b('在大模型上加一个小容量的“全局工作空间”模块，由门控写入并广播给各专家。', 'Add a small-capacity global-workspace module to large models, written through gates and broadcast to experts.'),
      b('用不确定性估计（如 Kadavath 2022 的自我评估）决定是否启动慢速推理。', 'Use uncertainty estimates (e.g. self-evaluation as in Kadavath 2022) to decide when to start slow reasoning.'),
    ],
    refs: ['miller2001', 'frank2001', 'dehaene2011', 'daw2005', 'vaswani2017', 'kadavath2022'],
  },
]
